// Package client provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package client

// Prefecture defines model for Prefecture.
type Prefecture struct {
	AnsType      string `json:"ansType"`
	CityName     string `json:"cityName"`
	FacilityAddr string `json:"facilityAddr"`
	FacilityCode string `json:"facilityCode"`
	FacilityId   string `json:"facilityId"`
	FacilityName string `json:"facilityName"`
	FacilityTel  string `json:"facilityTel"`
	FacilityType string `json:"facilityType"`
	Latitude     string `json:"latitude"`
	LocalGovCode string `json:"localGovCode"`
	Longitude    string `json:"longitude"`
	PrefName     string `json:"prefName"`
	SubmitDate   string `json:"submitDate"`
	ZipCode      string `json:"zipCode"`
}

// Prefectures defines model for Prefectures.
type Prefectures []Prefecture

