// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

// ErrorData defines model for ErrorData.
type ErrorData struct {

	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// PrefectureData defines model for PrefectureData.
type PrefectureData struct {
	Aichi     PrefectureHospitalData `json:"aichi"`
	Akita     PrefectureHospitalData `json:"akita"`
	Aomori    PrefectureHospitalData `json:"aomori"`
	Chiba     PrefectureHospitalData `json:"chiba"`
	Ehime     PrefectureHospitalData `json:"ehime"`
	Fukui     PrefectureHospitalData `json:"fukui"`
	Fukuoka   PrefectureHospitalData `json:"fukuoka"`
	Fukushima PrefectureHospitalData `json:"fukushima"`
	Gifu      PrefectureHospitalData `json:"gifu"`
	Gunma     PrefectureHospitalData `json:"gunma"`
	Hiroshima PrefectureHospitalData `json:"hiroshima"`
	Hokkaido  PrefectureHospitalData `json:"hokkaido"`
	Hyogo     PrefectureHospitalData `json:"hyogo"`
	Ibaraki   PrefectureHospitalData `json:"ibaraki"`
	Ishikawa  PrefectureHospitalData `json:"ishikawa"`
	Iwate     PrefectureHospitalData `json:"iwate"`
	Kagawa    PrefectureHospitalData `json:"kagawa"`
	Kagoshima PrefectureHospitalData `json:"kagoshima"`
	Kanagawa  PrefectureHospitalData `json:"kanagawa"`
	Kochi     PrefectureHospitalData `json:"kochi"`
	Kumamoto  PrefectureHospitalData `json:"kumamoto"`
	Kyoto     PrefectureHospitalData `json:"kyoto"`
	Mie       PrefectureHospitalData `json:"mie"`
	Miyagi    PrefectureHospitalData `json:"miyagi"`
	Miyazaki  PrefectureHospitalData `json:"miyazaki"`
	Nagano    PrefectureHospitalData `json:"nagano"`
	Nagasaki  PrefectureHospitalData `json:"nagasaki"`
	Nara      PrefectureHospitalData `json:"nara"`
	Niigata   PrefectureHospitalData `json:"niigata"`
	Oita      PrefectureHospitalData `json:"oita"`
	Okayama   PrefectureHospitalData `json:"okayama"`
	Okinawa   PrefectureHospitalData `json:"okinawa"`
	Osaka     PrefectureHospitalData `json:"osaka"`
	Saga      PrefectureHospitalData `json:"saga"`
	Saitama   PrefectureHospitalData `json:"saitama"`
	Shiga     PrefectureHospitalData `json:"shiga"`
	Shimane   PrefectureHospitalData `json:"shimane"`
	Shizuoka  PrefectureHospitalData `json:"shizuoka"`
	Tochigi   PrefectureHospitalData `json:"tochigi"`
	Tokushima PrefectureHospitalData `json:"tokushima"`
	Tokyo     PrefectureHospitalData `json:"tokyo"`
	Tottori   PrefectureHospitalData `json:"tottori"`
	Toyama    PrefectureHospitalData `json:"toyama"`
	Wakayama  PrefectureHospitalData `json:"wakayama"`
	Yamagata  PrefectureHospitalData `json:"yamagata"`
	Yamaguchi PrefectureHospitalData `json:"yamaguchi"`
	Yamanashi PrefectureHospitalData `json:"yamanashi"`
}

// PrefectureHospitalData defines model for PrefectureHospitalData.
type PrefectureHospitalData struct {

	// emergency peoples number
	Emergency int `json:"emergency"`

	// hospitalize peoples number
	Hospitalize int `json:"hospitalize"`

	// outPatient peoples number
	OutPatient int `json:"outPatient"`
}

// Prefectures defines model for Prefectures.
type Prefectures struct {
	Data PrefectureData `json:"data"`

	// get date
	Date  string     `json:"date"`
	Error *ErrorData `json:"error,omitempty"`
}

